config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  match "/404", to: "errors#not_found", via: :all, as: :not_found
  match "/500", to: "errors#internal_server_error", via: :all, as: :internal_server_error

  scope ":locale", locale: /en|pt-br|es/ do # /#{I18n.available_locales.join("|")}/
    root to: "home#index"

    # authentication
    devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
                       skip: :omniauth_callbacks,
                       controllers: { registrations: 'registrations' }

    resources :users, only: %i[show edit update] do
      scope module: "users" do
        resources :informations, only: %i[index update]
      end
      collection do
        get 'my_rooms' => 'users#my_rooms'
        get 'my_debates' => 'users#my_debates'
        get 'my_article' => 'users#my_articles'
      end
    end
    resources :rooms, except: %i[show]

    # resources :comments
    resources :debates do
      member do
        put 'upvote' => 'debates#upvote'
        put 'downvote' => 'debates#downvote'
      end
    end
    resources :articles do
      member do
        put 'upvote' => 'articles#upvote'
        put 'downvote' => 'articles#downvote'
      end
    end

    get '*path', to: "errors#not_found"
  end

  # when is put some route without :locale parameter,
  # with the language is done redirect
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '', to: redirect("/#{I18n.default_locale}")
end

app/models/user.rb
class User < ApplicationRecord
  include Omniauthenticable
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: %i(google_oauth2 facebook)

  # mount_uploader :avatar, ImageUserUploader

  has_many :user_known_languages, dependent: :destroy
  has_many :known_languages, through: :user_known_languages, class_name: 'Language', foreign_key: 'known_languages_id'
  has_many :user_languages_studieds, dependent: :destroy
  has_many :languages_studied, through: :user_languages_studieds, class_name: 'Language', foreign_key: 'languages_studied_id'
  has_many :rooms, dependent: :destroy
  has_many :debates, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :postings, dependent: :destroy

  validates :username, presence: true
  validates :username, :email, uniqueness: true

  accepts_nested_attributes_for :user_known_languages, allow_destroy: true
  accepts_nested_attributes_for :user_languages_studieds, allow_destroy: true

  enum gender: %i[M F]

  acts_as_voter

  # def self.from_omniauth(data)
  #   where(email: data['email']).first_or_create do |user|
  #     user.username = data.name.parameterize.underscore
  #     user.first_name = data.first_name
  #     user.last_name = data.last_name
  #     user.email = data.email
  #     user.password = Devise.friendly_token[0, 20]
  #     user.avatar = data.image
  #   end
  # end

  def to_param
    "#{id} #{username}".parameterize
  end
end

app/controllers/users/informations_controller.rb
class Users::InformationsController < ApplicationController
  before_action :set_languages, only: %i[index]

  def index
    current_user.user_known_languages.build
    current_user.user_languages_studieds.build
  end

  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user.id), notice: t('devise.registrations.signed_up')
    else
      redirect_to user_informations_path(current_user)
    end
  end

  private
  def user_params
    params.require(:user)
          .permit(:country,
                  user_known_languages_attributes: %i[
                    id known_languages_id speak write _destroy
                  ],
                  user_languages_studieds_attributes: %i[
                    id languages_studied_id speak write _destroy
                  ])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update]
  before_action :set_languages, only: %i[edit update]
  before_action :sanitize_page_params, only: %i[update create]
  before_action :authenticate_user!

  def show
    authorize! :show, @user
    @rooms = Room.includes_for_room.desc_with_limit 6
    @debates = Debate.includes_for_postings.desc_with_limit 4
    @articles = Article.includes_for_postings.desc_with_limit 4
  end

  def edit
    authorize! :edit, @user
  end

  def update
    avatar = params[:user][:avatar]
    params[:user][:avatar] = UploadService.process(avatar) if avatar.present?
    if @user.update(user_params)
      redirect_to @user, notice: t('.notice')
    else
      render :edit
    end
  end

  def my_rooms
    @rooms = current_user.rooms
  end

  def my_debates
    @debates = current_user.debates
  end

  def my_articles
    @articles = current_user.articles
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def sanitize_page_params
    params[:user][:gender] = params[:user][:gender].to_i
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user)
          .permit(:first_name, :last_name, :gender, :username, :email, :password,
                  :avatar, :born_on, :password_confirmation, :country, :bio, :phone,
                  user_known_languages_attributes: %i[
                    id known_languages_id speak write _destroy
                  ],
                  user_languages_studieds_attributes: %i[
                    id languages_studied_id speak write _destroy
                  ])
  end
end

app/helpers/user_helper.rb
module UserHelper
  def profile_incomplete?(user)
    user.avatar.blank? || user.phone.blank? || user.born_on.blank?
  end
end

app/views/users/shared/_aside.html.erb
<div class="user-aside-section container-default">
  <div class="user-aside-header">
    <%= link_to edit_user_path(current_user) do %>
      <%= render partial: "shared/user/avatar" %>
    <% end %>
    <p class="no-marging"><%= current_user.username %></p>
    <p class="no-marging"> <%= t 'rooms_text' %>: <%= current_user.created_rooms %></p>
    <p class="no-marging"> <%= t 'articles_text' %>: <%= current_user.created_articles %></p>
    <p class="no-marging"> Debates: <%= current_user.created_debates %></p>
    <% if profile_incomplete? current_user %>
      <p class="m-2 red"> Seu perfil está incompleto!  </p>
    <% end %>
  </div>
  <div class="list-group">
    <%= link_to t('my_rooms'), my_rooms_users_url, class: 'list-group-item my-rooms' %>
    <%= link_to t('my_debates'), my_debates_users_url, class: 'list-group-item my-debates' %>
    <%= link_to t('my_articles'), my_article_users_url, class: 'list-group-item my-articles' %>
    <!-- <a href="#" class="list-group-item">Estatisticas</a> -->
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if controller_name != 'sessions' %>
  Have an account? <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  Need an account? <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%#- if devise_mapping.omniauthable? %>
  <%#- resource_class.omniauth_providers.each do |provider| %>
    <%#= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <%# end -%>
<%# end -%>