config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  match "/404", to: "errors#not_found", via: :all, as: :not_found
  match "/500", to: "errors#internal_server_error", via: :all, as: :internal_server_error

  scope ":locale", locale: /en|pt-br|es/ do # /#{I18n.available_locales.join("|")}/
    root to: "home#index"

    # authentication
    devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
                       skip: :omniauth_callbacks,
                       controllers: { registrations: 'registrations' }

    resources :users, only: %i[show edit update] do
      scope module: "users" do
        resources :informations, only: %i[index update]
      end
      collection do
        get 'my_rooms' => 'users#my_rooms'
        get 'my_debates' => 'users#my_debates'
        get 'my_article' => 'users#my_articles'
      end
    end
    resources :rooms, except: %i[show]

    # resources :comments
    resources :debates do
      member do
        put 'upvote' => 'debates#upvote'
        put 'downvote' => 'debates#downvote'
      end
    end
    resources :articles do
      member do
        put 'upvote' => 'articles#upvote'
        put 'downvote' => 'articles#downvote'
      end
    end

    get '*path', to: "errors#not_found"
  end

  # when is put some route without :locale parameter,
  # with the language is done redirect
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '', to: redirect("/#{I18n.default_locale}")
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # TODO: add this when admin will be add
    # if user.admin?
    #   can :manage, :all
    # else
    can [:show, :destroy, :edit], User do |uu|
      uu == user
    end

    can [:edit, :update, :destroy], Room do |room|
      room.user == user
    end

    can [:edit, :update, :destroy], Posting do |posting|
      posting.user == user
    end

    # end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  scope :includes_for_postings, -> { includes(:language, :user, :category) }
  scope :desc_with_limit, ->(limit = 100) { order(created_at: :desc).limit(limit) }
end

app/models/article.rb
class Article < Posting
  belongs_to :user, counter_cache: :created_articles
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :postings, dependent: :destroy

  validates :title, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :posting
  validates :content, presence: true
end

app/models/debate.rb
class Debate < Posting
  belongs_to :user, counter_cache: :created_debates
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :rooms, dependent: :destroy
  has_many :user_known_languages, dependent: :destroy
  has_many :users, through: :user_known_languages
  has_many :user_languages_studieds, dependent: :destroy
  has_many :users, through: :user_languages_studieds
  has_many :postings, dependent: :destroy

  validates :name, :shortcode, presence: true
end

app/models/posting.rb
class Posting < ApplicationRecord
  belongs_to :language
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true

  acts_as_votable

  def to_param
    "#{id} #{title}".parameterize
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user, counter_cache: :created_rooms
  belongs_to :language

  validates :link, :level, presence: true

  validates :link, uniqueness: true

  scope :includes_for_room, -> { includes(:language, :user) }
end

app/models/user.rb
class User < ApplicationRecord
  include Omniauthenticable
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: %i(google_oauth2 facebook)

  # mount_uploader :avatar, ImageUserUploader

  has_many :user_known_languages, dependent: :destroy
  has_many :known_languages, through: :user_known_languages, class_name: 'Language', foreign_key: 'known_languages_id'
  has_many :user_languages_studieds, dependent: :destroy
  has_many :languages_studied, through: :user_languages_studieds, class_name: 'Language', foreign_key: 'languages_studied_id'
  has_many :rooms, dependent: :destroy
  has_many :debates, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :postings, dependent: :destroy

  validates :username, presence: true
  validates :username, :email, uniqueness: true

  accepts_nested_attributes_for :user_known_languages, allow_destroy: true
  accepts_nested_attributes_for :user_languages_studieds, allow_destroy: true

  enum gender: %i[M F]

  acts_as_voter

  # def self.from_omniauth(data)
  #   where(email: data['email']).first_or_create do |user|
  #     user.username = data.name.parameterize.underscore
  #     user.first_name = data.first_name
  #     user.last_name = data.last_name
  #     user.email = data.email
  #     user.password = Devise.friendly_token[0, 20]
  #     user.avatar = data.image
  #   end
  # end

  def to_param
    "#{id} #{username}".parameterize
  end
end

app/models/user_known_language.rb
class UserKnownLanguage < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :known_languages, class_name: 'Language'

  enum level: %i[begginer upper_begginer intermediate
                 upper_intermediate advanced upper_advanced
                 native]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to user_path(current_user) if user_signed_in?
  end
end

app/controllers/posting_controller.rb
class PostingController < ApplicationController
  before_action :set_languages, only: %i[new edit create index]
  before_action :set_categories, only: %i[new edit create index]
  before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_nav_bar?(action, controller)
    (action == 'new' && controller == 'sessions') ||
    (action == 'new' && controller == 'registrations')
  end

  def show_footer?(action, controller)
    (action == 'new' && controller == 'sessions') ||
    (action == 'new' && controller == 'registrations')
  end

  def flash_message
    messages = ''
    %i[success info warning danger].each do |type|
      if flash[type]
        messages += "<p class=\"alert alert-#{type}\">#{flash[type]}</p>"
      end
    end
    messages
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/debates_helper.rb
module DebatesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML
    <div class="alert alert-danger">
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end
end

app/helpers/hello_page_helper.rb
module HelloPageHelper
end

app/helpers/language_helper.rb
module LanguageHelper
  def numbers_levels
    select_levels([0, 1, 2, 3, 4, 5, 6])
  end

  def string_levels
    select_levels(%w[begginer upper_begginer intermediate
                     upper_intermediate advanced upper_advanced
                     native])
  end

  private

  def select_levels(value)
    [
      [t('begginer'), value[0]],
      [t('upper_begginer'), value[1]],
      [t('intermediate'), value[2]],
      [t('upper_intermediate'), value[3]],
      [t('advanced'), value[4]],
      [t('upper_advanced'), value[5]],
      [t('native'), value[6]]
    ]
  end
end

app/helpers/user_helper.rb
module UserHelper
  def profile_incomplete?(user)
    user.avatar.blank? || user.phone.blank? || user.born_on.blank?
  end
end

app/views/shared/posting/_index.html.erb
<% form_link, new_resource, title = if type == "debate" %>
  <% [debates_path, new_debate_path, 'Debates'] %>
<% else %>
  <% [articles_path, new_article_path, t('articles_text')] %>
<% end %>

<div class="container">
  <div class="container-default">
    <div class="row">
      <div class="col-lg-8">
        <h1><%= title %></h1>
      </div>
      <div class="col-lg-4">
        <%= link_to t('create_debate'), new_resource, class: 'float-right' %>
      </div>
    </div>
    <%= form_tag form_link, method: :get do %>
      <div class="row">
        <div class="col-lg-auto">
          <%= label_tag Posting.human_attribute_name(:language) %><br />
          <%= select_tag("language", options_for_select(@languages, params[:language]), class: 'custom-select', include_blank: true) %>
        </div>
        <div class="col-lg-auto">
          <%= label_tag Posting.human_attribute_name(:category) %><br />
          <%= select_tag("category", options_for_select(@categories, params[:category]), class: 'custom-select', include_blank: true) %>
        </div>
        <div class="col-lg-auto mt-4">
          <%= submit_tag 'filter', class: 'btn btn-bnativus' %>
        </div>
      </div>
    <% end %>
    <% unless postings.empty? %>
      <div class="row">
        <%= render partial: "shared/posting/posting_card", collection: postings, as: :posting %>
      </div>
    <% else %>
      <h2 class="text-center mt-4 mb-4"> <%= t 'result_not_found' %> </h2>
    <% end %>
  </div>
</div>

app/views/shared/posting/_posting_card.html.erb
<div class="col-lg-12 col-lg-6 mt-3 model-card">
  <div class="card h-100">
    <div class="card-body">
      <div class="pull-left card-created-at">
        <%= t time_ago_in_words posting.created_at %>
      </div>
      <div class="share-link-card pull-right">
        <a href="" class="btn-facebook" data-link="<%= debate_url(posting) %>">
          <i class="fa fa-facebook" aria-hidden="true"></i>
        </a>
        <a href="" class="btn-twitter" data-link="<%= debate_url(posting) %>">
          <i class="fa fa-twitter" aria-hidden="true"></i>
        </a>
      </div>
      <div class="card-actions pull-right">
        <% if can? :update, posting %>
          <% edit_link = posting.type == "Debate" ? edit_debate_path(posting) : edit_article_path(posting) %>
          <%= link_to(edit_link) do %>
            <i class="fa fa-pencil" aria-hidden="true"></i>
          <% end %>
        <% end %>
        <% if can? :destroy, posting %>
          <%= link_to(posting, method: :delete, data: { confirm: t('sure?') }) do %>
            <i class="fa fa-trash" aria-hidden="true"></i>
          <% end %>
        <% end %>
      </div>
      <hr>
      <%= link_to(posting, class: 'model-link') do %>
        <div class="row">
          <div class="col-lg-2">
            <% if posting.user.avatar.blank? %>
              <%= image_tag("profile-icon.png", class: 'card-img-top')  %>
            <% else %>
              <%= cl_image_tag(posting.user.avatar, class: 'card-img-top') %>
            <% end %>
          </div>
          <div class="col-lg-10">
            <h4><%= t posting.title %></h4>
            <p class="card-username-posting"><%= posting.user.username %></p>
            <div class="row">
              <div class="col-lg-auto">
                <h6> <i class="fa fa-globe" aria-hidden="true"></i> <%= t posting.language.name %> </h6>
              </div>
              <div class="col-lg-auto">
                <h6> <i class="fa fa-tag" aria-hidden="true"></i> <%= t posting.category.title %> </h6>
              </div>
              <div class="col-lg-auto">
                <h6> <i class="fa fa-eye" aria-hidden="true"></i> <%= t posting.views %> </h6>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/posting/_show.html.erb
<div class="container">
  <div class="container-default">
    <div class="row">
      <div class="col-lg-2 text-center">
        <% if posting.user.avatar.blank? %>
          <%= image_tag("profile-icon.png", class: 'card-img-top')  %>
        <% else %>
          <%= cl_image_tag(posting.user.avatar, class: 'card-img-top') %>
        <% end %>
        <div class="row">
          <div class="col-lg-12">
            <%= posting.user.username %>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <%= t posting.language.name %>
          </div>
        </div>
      </div>
      <div class="col-lg-10">
        <div class="font-tiny dark-grey">
          <i class="fa fa-eye" aria-hidden="true"></i> <%= posting.views %> |
          <i class="fa fa-tag" aria-hidden="true"></i> <%= posting.category.title %>
        </div>
        <h1><%= posting.title %></h1>
        <hr>
        <%= raw posting.content %>
        <br>
        <div class="posting-votes">
          <% upvote_link = posting.type == "Debate" ? upvote_debate_path(posting) : upvote_article_path(posting) %>
          <%= link_to(upvote_link, method: :put) do %>
            <i class="fa fa-thumbs-up" aria-hidden="true"></i>
          <% end %>
          <%= posting.get_upvotes.size%>

          <% downvote_link = posting.type == "Debate" ? downvote_debate_path(posting) : downvote_article_path(posting) %>
          <%= link_to(downvote_link, method: :put) do %>
            <i class="fa fa-thumbs-down" aria-hidden="true"></i>
          <% end %>
          <%= posting.get_downvotes.size%>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container mt-4">
  <div class="container-default">
    <div id="disqus_thread"></div>
  </div>
</div>

<script>
var disqus_config = function () {
  this.page.shortname = 'bnativus';
  this.page.identifier = '<%= posting.id%>';
  this.page.title = '<%= posting.title %>';
  this.page.url = '<%= request.original_url %>';
  this.language = "<%= I18n.locale %>";
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://bnativus.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>