config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  match "/404", to: "errors#not_found", via: :all, as: :not_found
  match "/500", to: "errors#internal_server_error", via: :all, as: :internal_server_error

  scope ":locale", locale: /en|pt-br|es/ do # /#{I18n.available_locales.join("|")}/
    root to: "home#index"

    # authentication
    devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
                       skip: :omniauth_callbacks,
                       controllers: { registrations: 'registrations' }

    resources :users, only: %i[show edit update] do
      scope module: "users" do
        resources :informations, only: %i[index update]
      end
      collection do
        get 'my_rooms' => 'users#my_rooms'
        get 'my_debates' => 'users#my_debates'
        get 'my_article' => 'users#my_articles'
      end
    end
    resources :rooms, except: %i[show]

    # resources :comments
    resources :debates do
      member do
        put 'upvote' => 'debates#upvote'
        put 'downvote' => 'debates#downvote'
      end
    end
    resources :articles do
      member do
        put 'upvote' => 'articles#upvote'
        put 'downvote' => 'articles#downvote'
      end
    end

    get '*path', to: "errors#not_found"
  end

  # when is put some route without :locale parameter,
  # with the language is done redirect
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '', to: redirect("/#{I18n.default_locale}")
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user, counter_cache: :created_rooms
  belongs_to :language

  validates :link, :level, presence: true

  validates :link, uniqueness: true

  scope :includes_for_room, -> { includes(:language, :user) }
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[edit update destroy]
  before_action :set_languages, only: %i[new edit create index]
  before_action :authenticate_user!

  def index
    @rooms = Room.includes(:language, :user).all
    @rooms = @rooms.where('language_id = ?', params[:language]) unless params[:language].blank?
    @rooms = @rooms.where('level = ?', params[:level]) unless params[:level].blank?
  end

  def new
    @room = Room.new
  end

  def edit
    authorize! :edit, @room
  end

  def create
    @room = Room.new(room_params)
    @room.user = current_user
    @room.ip = request.remote_ip

    if @room.save
      redirect_to user_path(current_user), notice: t('.notice')
    else
      render :new
    end
  end

  def update
    if @room.update(room_params)
      redirect_to user_path(current_user), notice: t('.notice')
    else
      render :edit
    end
  end

  def destroy
    authorize! :destroy, @room
    @room.destroy
    redirect_to user_path(current_user), notice: t('.notice')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def room_params
    params.require(:room).permit(:link, :level, :language_id)
  end
end

app/views/rooms/_form.html.erb
<div class="create-room-form">
  <%= form_with(model: room, local: true) do |form| %>
    <%= render partial: "shared/form_messages", locals: {model: room} %>

    <div class="form-group">
      <%= form.label Room.human_attribute_name(:language) %>
      <br>
      <%= form.select(:language_id, @languages, {}, { class: 'custom-select' }) %>
    </div>

    <div class="form-group">
      <%= form.label Room.human_attribute_name(:level) %>
      <br>
      <%= form.select(:level, [], {}, { :class => 'custom-select' }) do %>
        <%= options_for_select(string_levels) %>
      <% end %>
    </div>

    <div class="form-group">
      <%= form.label :link %>
      <small>
        <a href="" data-toggle="modal" data-target="#exampleModalLong">
          <%= t ('room_form.what_is_it') %></a>
      </small>
      <div class="row">
        <div class="col-lg-10">
          <%= form.text_field :link, class: 'form-control', id: 'link-room' %>
        </div>
        <div class="col-lg-2">
          <button type="button" class="btn btn-info" id="btn-copy" name="button">
            <%= t ('room_form.copy') %>
          </button>
        </div>
      </div>
    </div>
    <div class="actions">
      <%= form.submit 'Done', class: 'btn btn-success' %>
    </div>
  <% end %>

  <!-- Modal -->
  <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <!-- <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5> -->
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= t('room_form.create_room_description') %>:
          <hr>
          1.
          <%= t 'room_form.step_1' %>
          <a href="https://accounts.google.com/SignUp" target="_blank">Google</a><br>
          2.
          <%= t 'room_form.step_2' %>
          <a href="https://hangouts.google.com" target="_blank">
            Google Hangout
          </a><br>
          3.
          <%= t 'room_form.step_3' %>:
          <%= image_tag("tutorial.gif", id: 'create-room-tutorial')  %>
          <br>
          4.
          <%= t 'room_form.step_4' %>
          <br>
          5.
          <%= t 'room_form.step_5' %>
          <br>
        </div>
        <!-- <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div> -->
      </div>
    </div>
  </div>
</div>

app/views/rooms/edit.html.erb
<div class="container container-default">
  <h1>Editing Room</h1>
  <%= render 'form', room: @room %>
</div>

app/views/rooms/index.html.erb
<div class="container index-rooms">
  <div class="container-default">
    <div class="row">
      <div class="col-lg-8">
        <h1><%= t 'rooms_text' %></h1>
      </div>
      <div class="col-lg-4">
        <%= link_to t('create_room'), new_room_url, class: 'float-right' %>
      </div>
    </div>
    <%= form_tag rooms_path, method: :get do %>
      <div class="row">
        <div class="col-lg-auto">
          <%= label_tag Room.human_attribute_name(:language) %><br />
          <%= select_tag("language", options_for_select(@languages, params[:language]), class: 'custom-select', include_blank: true) %>
        </div>
        <div class="col-lg-auto">
          <%= label_tag Room.human_attribute_name(:level) %><br />
          <%= select_tag("level", options_for_select(string_levels, params[:level]), class: 'custom-select', include_blank: true) %>
        </div>
        <div class="col-lg-auto mt-4">
          <%= submit_tag 'filter', class: 'btn btn-bnativus' %>
        </div>
      </div>
    <% end %>
    <% unless @rooms.empty? %>
      <div class="row">
        <%= render partial: "shared/room_card", collection: @rooms, as: :room %>
      </div>
    <% else %>
      <h2 class="text-center mt-4 mb-4"> <%= t 'result_not_found' %> </h2>
    <% end %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="container container-default">
  <h1>New Room</h1>

  <%= render 'form', room: @room %>
</div>